apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomin-jungdok
  labels:
    app: gomin-jungdok
spec:
  replicas: 3 # 파드 복제본 수
  selector:
    matchLabels:
      app: gomin-jungdok
  template:
    metadata:
      labels:
        app: gomin-jungdok
    spec:
      containers:
      - name: noguet-container
        image: jjwon0407/gomin_jungdok:latest # 사용하는 Docker 이미지
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # 컨테이너 내부에서 사용하는 포트
        resources: # 리소스 요청 및 제한 (옵션)
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: gomin-jungdok-service
  labels:
    app: gomin-jungdok
spec:
  selector:
    app: gomin-jungdok
  type: LoadBalancer # 외부에서 접근 가능하도록 설정
  ports:
  - protocol: TCP
    port: 8080 # 외부에서 노출할 포트
    targetPort: 8080 # 컨테이너 내부 포트